### ISSUE TITLE
Wordlists

### ISSUE THREAD

**Issue by gekoke** [redcode-labs/RedNix#8]
It would be cool if this flake exported a collection of wordlists, similar to what's bundled with Kali Linux - either as part of a package or as files placed in a `nixosConfiguration`.

**Comment by unrooted** [comment]
hi, currently there is such a thing available within `packages.nix` file - they're sorted by their category

I suppose that's what you've meant...? If so, you can easily tweak it or use it via devShells - for example `nix develop .#bluetooth` - and so you'd get a devshell with all the packages within the `bluetooth` category.

For more info about devShells in this project, you can read their wiki page: https://github.com/redcode-labs/RedNix/wiki/3.-devShells
